// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: v1/space.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分页
type PageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页
	Page int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty" dc:"当前页"`
	// 当前页条数
	Size int64 `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty" dc:"当前页条数"`
	// 排序字段
	Order string `protobuf:"bytes,3,opt,name=Order,proto3" json:"Order,omitempty" dc:"排序字段"`
	// 升序/降序
	Sort string `protobuf:"bytes,4,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"升序/降序...其他参数自行添加"` // ...其他参数自行添加
}

func (x *PageReq) Reset() {
	*x = PageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReq) ProtoMessage() {}

func (x *PageReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReq.ProtoReflect.Descriptor instead.
func (*PageReq) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{0}
}

func (x *PageReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *PageReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前页
	Page int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty" dc:"当前页"`
	// 当前页条数
	Size int64 `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty" dc:"当前页条数"`
	// 总数
	Total int64 `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty" dc:"总数"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ItemType:
	//
	//	*ListItem_Id
	ItemType isListItem_ItemType `protobuf_oneof:"item_type" dc:"*ListItem_Id"`
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{2}
}

func (m *ListItem) GetItemType() isListItem_ItemType {
	if m != nil {
		return m.ItemType
	}
	return nil
}

func (x *ListItem) GetId() int64 {
	if x, ok := x.GetItemType().(*ListItem_Id); ok {
		return x.Id
	}
	return 0
}

type isListItem_ItemType interface {
	isListItem_ItemType()
}

type ListItem_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3,oneof" dc:"列表每一项类型"` // 列表每一项类型
}

func (*ListItem_Id) isListItem_ItemType() {}

type PageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List       []*ListItem `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Pagination *Pagination `protobuf:"bytes,2,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
}

func (x *PageRes) Reset() {
	*x = PageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRes) ProtoMessage() {}

func (x *PageRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRes.ProtoReflect.Descriptor instead.
func (*PageRes) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{3}
}

func (x *PageRes) GetList() []*ListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PageRes) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// 列表
type ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 排序字段
	Order string `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty" dc:"排序字段"`
	// 升序/降序
	Sort string `protobuf:"bytes,2,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"升序/降序"`
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{4}
}

func (x *ListReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ListItem `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *ListRes) Reset() {
	*x = ListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRes) ProtoMessage() {}

func (x *ListRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRes.ProtoReflect.Descriptor instead.
func (*ListRes) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{5}
}

func (x *ListRes) GetList() []*ListItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 删除
type DeletReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletReq) Reset() {
	*x = DeletReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletReq) ProtoMessage() {}

func (x *DeletReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletReq.ProtoReflect.Descriptor instead.
func (*DeletReq) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{6}
}

type DeletRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=Ids,proto3" json:"Ids,omitempty" v:"required"` // v: required
}

func (x *DeletRes) Reset() {
	*x = DeletRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletRes) ProtoMessage() {}

func (x *DeletRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletRes.ProtoReflect.Descriptor instead.
func (*DeletRes) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{7}
}

func (x *DeletRes) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 新增
type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{8}
}

type AddRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRes) Reset() {
	*x = AddRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRes) ProtoMessage() {}

func (x *AddRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRes.ProtoReflect.Descriptor instead.
func (*AddRes) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{9}
}

// 详情
type InfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" v:"required"` // v: required
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{10}
}

func (x *InfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfoRes) Reset() {
	*x = InfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRes) ProtoMessage() {}

func (x *InfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRes.ProtoReflect.Descriptor instead.
func (*InfoRes) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{11}
}

// 更新
type UpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" v:"required"` // v: required
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRes) Reset() {
	*x = UpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRes) ProtoMessage() {}

func (x *UpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRes.ProtoReflect.Descriptor instead.
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{13}
}

type OssSignReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// OSS目录
	Dir string `protobuf:"bytes,1,opt,name=Dir,proto3" json:"Dir,omitempty" dc:"OSS目录" v:"required"` // v: required
	// 用户ID
	Uid int64 `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty" dc:"用户ID" v:"required"` // v: required
}

func (x *OssSignReq) Reset() {
	*x = OssSignReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OssSignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssSignReq) ProtoMessage() {}

func (x *OssSignReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssSignReq.ProtoReflect.Descriptor instead.
func (*OssSignReq) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{14}
}

func (x *OssSignReq) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *OssSignReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type OssSignRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 授权信息
	Policy string `protobuf:"bytes,1,opt,name=Policy,proto3" json:"Policy,omitempty" dc:"授权信息"`
	// 授权Key
	OSSAccessKeyId string `protobuf:"bytes,2,opt,name=OSSAccessKeyId,proto3" json:"OSSAccessKeyId,omitempty" dc:"授权Key"`
	// 授权签名
	Signature string `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty" dc:"授权签名"`
	// 授权域名
	Host string `protobuf:"bytes,4,opt,name=Host,proto3" json:"Host,omitempty" dc:"授权域名"`
	// 目录UIDKey
	Key string `protobuf:"bytes,5,opt,name=Key,proto3" json:"Key,omitempty" dc:"目录UIDKey"`
	// 上传成功的回调状态码
	SUCCESS_ACTION_STATUS int32 `protobuf:"varint,6,opt,name=SUCCESS_ACTION_STATUS,json=SUCCESSACTIONSTATUS,proto3" json:"SUCCESS_ACTION_STATUS,omitempty" dc:"上传成功的回调状态码"`
}

func (x *OssSignRes) Reset() {
	*x = OssSignRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_space_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OssSignRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OssSignRes) ProtoMessage() {}

func (x *OssSignRes) ProtoReflect() protoreflect.Message {
	mi := &file_v1_space_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OssSignRes.ProtoReflect.Descriptor instead.
func (*OssSignRes) Descriptor() ([]byte, []int) {
	return file_v1_space_proto_rawDescGZIP(), []int{15}
}

func (x *OssSignRes) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *OssSignRes) GetOSSAccessKeyId() string {
	if x != nil {
		return x.OSSAccessKeyId
	}
	return ""
}

func (x *OssSignRes) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *OssSignRes) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *OssSignRes) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *OssSignRes) GetSUCCESS_ACTION_STATUS() int32 {
	if x != nil {
		return x.SUCCESS_ACTION_STATUS
	}
	return 0
}

var File_v1_space_proto protoreflect.FileDescriptor

var file_v1_space_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x5b, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x53, 0x6f, 0x72, 0x74, 0x22, 0x4a, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x29, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02, 0x49, 0x64, 0x42, 0x0b,
	0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x61, 0x0a, 0x07, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33,
	0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53,
	0x6f, 0x72, 0x74, 0x22, 0x2e, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x23,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x0a, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x22,
	0x1c, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x49, 0x64, 0x73, 0x22, 0x08, 0x0a,
	0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x22, 0x08, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x22, 0x19, 0x0a, 0x07, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x09, 0x0a, 0x07,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x1b, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x22, 0x30, 0x0a, 0x0a, 0x4f, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x69,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x55, 0x69, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x0a, 0x4f, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x52,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x4f, 0x53,
	0x53, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x4f, 0x53, 0x53, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x48, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x15, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x32, 0xfc, 0x01, 0x0a, 0x04, 0x43,
	0x72, 0x75, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x03, 0x41,
	0x64, 0x64, 0x12, 0x0d, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x29, 0x0a, 0x05, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x26, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x32, 0x36, 0x0a, 0x03, 0x4f, 0x73, 0x73,
	0x12, 0x2f, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x11, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x4f, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x4f, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x76, 0x65, 0x72, 0x61, 0x2d, 0x62, 0x79, 0x74, 0x65, 0x2f, 0x63, 0x6f, 0x6f, 0x6c, 0x2d, 0x67,
	0x6f, 0x2d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_space_proto_rawDescOnce sync.Once
	file_v1_space_proto_rawDescData = file_v1_space_proto_rawDesc
)

func file_v1_space_proto_rawDescGZIP() []byte {
	file_v1_space_proto_rawDescOnce.Do(func() {
		file_v1_space_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_space_proto_rawDescData)
	})
	return file_v1_space_proto_rawDescData
}

var file_v1_space_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_space_proto_goTypes = []interface{}{
	(*PageReq)(nil),    // 0: space.PageReq
	(*Pagination)(nil), // 1: space.Pagination
	(*ListItem)(nil),   // 2: space.ListItem
	(*PageRes)(nil),    // 3: space.PageRes
	(*ListReq)(nil),    // 4: space.ListReq
	(*ListRes)(nil),    // 5: space.ListRes
	(*DeletReq)(nil),   // 6: space.DeletReq
	(*DeletRes)(nil),   // 7: space.DeletRes
	(*AddReq)(nil),     // 8: space.AddReq
	(*AddRes)(nil),     // 9: space.AddRes
	(*InfoReq)(nil),    // 10: space.InfoReq
	(*InfoRes)(nil),    // 11: space.InfoRes
	(*UpdateReq)(nil),  // 12: space.UpdateReq
	(*UpdateRes)(nil),  // 13: space.UpdateRes
	(*OssSignReq)(nil), // 14: space.OssSignReq
	(*OssSignRes)(nil), // 15: space.OssSignRes
}
var file_v1_space_proto_depIdxs = []int32{
	2,  // 0: space.PageRes.List:type_name -> space.ListItem
	1,  // 1: space.PageRes.Pagination:type_name -> space.Pagination
	2,  // 2: space.ListRes.List:type_name -> space.ListItem
	0,  // 3: space.Crud.Page:input_type -> space.PageReq
	8,  // 4: space.Crud.Add:input_type -> space.AddReq
	6,  // 5: space.Crud.Delet:input_type -> space.DeletReq
	10, // 6: space.Crud.Info:input_type -> space.InfoReq
	12, // 7: space.Crud.Update:input_type -> space.UpdateReq
	4,  // 8: space.Crud.List:input_type -> space.ListReq
	14, // 9: space.Oss.SignUrl:input_type -> space.OssSignReq
	3,  // 10: space.Crud.Page:output_type -> space.PageRes
	9,  // 11: space.Crud.Add:output_type -> space.AddRes
	7,  // 12: space.Crud.Delet:output_type -> space.DeletRes
	11, // 13: space.Crud.Info:output_type -> space.InfoRes
	13, // 14: space.Crud.Update:output_type -> space.UpdateRes
	5,  // 15: space.Crud.List:output_type -> space.ListRes
	15, // 16: space.Oss.SignUrl:output_type -> space.OssSignRes
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_v1_space_proto_init() }
func file_v1_space_proto_init() {
	if File_v1_space_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_space_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OssSignReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_space_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OssSignRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_space_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ListItem_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_space_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_space_proto_goTypes,
		DependencyIndexes: file_v1_space_proto_depIdxs,
		MessageInfos:      file_v1_space_proto_msgTypes,
	}.Build()
	File_v1_space_proto = out.File
	file_v1_space_proto_rawDesc = nil
	file_v1_space_proto_goTypes = nil
	file_v1_space_proto_depIdxs = nil
}
